"""new fields in user model

Revision ID: 01de954f76d6
Revises: 44a4dddd4574
Create Date: 2019-02-24 16:03:53.903835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01de954f76d6'
down_revision = '44a4dddd4574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
